### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by networker45** [nicovell3/DNSWaterTorture#1]
Hi,

How can I fix the error  ? My dns list https://public-dns.info/nameservers.txt

Regards

panic: runtime error: index out of range

goroutine 21305 [running]:
math/rand.(*rngSource).Uint64(...)
        /usr/lib/go-1.11/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(0xc0000a9500, 0x3591cdf16b7ea68f)
        /usr/lib/go-1.11/src/math/rand/rng.go:234 +0x89
math/rand.(*Rand).Int63(0xc00008e4e0, 0x3591cdf16b7ea68f)
        /usr/lib/go-1.11/src/math/rand/rand.go:85 +0x33
math/rand.(*Rand).Int31(0xc00008e4e0, 0xc03591cdf1)
        /usr/lib/go-1.11/src/math/rand/rand.go:99 +0x2b
math/rand.(*Rand).Int31n(0xc00008e4e0, 0x1a, 0xc00000000d)
        /usr/lib/go-1.11/src/math/rand/rand.go:134 +0x4f
math/rand.(*Rand).Intn(0xc00008e4e0, 0x1a, 0xd)
        /usr/lib/go-1.11/src/math/rand/rand.go:172 +0x45
main.randomString(0x8, 0xc00009e018, 0xf4240)
        /root/DNSWaterTorture/watertorture.go:23 +0xac
main.attack(0xc00009e240, 0x7ffe8a747794, 0xe, 0xc0001d66e0, 0xa, 0xffffffffffffffff, 0x3e8)
        /root/DNSWaterTorture/watertorture.go:47 +0x14c
created by main.main
        /root/DNSWaterTorture/watertorture.go:113 +0x433
exit status 2

**Comment by nicovell3** [comment]
Hello @networker45 ,

Have you modified the code? I have just implemented a test for the randomString function, but I cannot replicate your error.

Can you give me more information about your environment please?

Best regards!
Nico.

**Comment by nicovell3** [comment]
Closed due to inactivity
